apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: astroml

resources:
  - namespace.yaml
  - postgres-deployment.yaml
  - redis-deployment.yaml
  - astroml-deployment.yaml
  - rbac.yaml

commonLabels:
  managed-by: kustomize
  app: astroml

commonAnnotations:
  version: "1.0.0"
