"""API routers package.

Organized by version under api/routers/v1/.
"""

from api.routers.v1 import (
    accounts_router,
    agents_router,
    alerts_router,
    audit_router,
    auth_router,
    backup_router,
    chat_router,
    compliance_router,
    contact_router,
    contributors_router,
    cost_router,
    discussions_router,
    errors_router,
    explanations_router,
    faq_router,
    feedback_router,
    fraud_router,
    llm_cache_metrics_router,
    llm_health_router,
    llm_metrics_router,
    llm_router,
    llm_usage_router,
    loyalty_router,
    mentorship_router,
    models_router,
    monitoring_router,
    notifications_router,
    onboarding_router,
    query_router,
    rate_limit_router,
    reports_router,
    search_router,
    stream_router,
    streaming_router,
    transactions_router,
    validation_router,
    voice_router,
    ws_router,
)
